server:
  port: 8203

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://condonuitydev.mysql.database.azure.com:3306/condonuitydev
    username: condonuitydev.mysql.database.azure.com
    password: A#C<)}5gCnP8qQv

spring.jpa:
  hibernate:
    connection:
      charset: utf8
      useUnicode: true
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect


