server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignoredServices: '*'
  routes:
    user-service:
      path: /users/**
      serviceId: user-service
      stripPrefix: true
    auth-service:
      path: /auth/**
      serviceId: auth-service
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie
    client-service:
      path: /clients/**
      serviceId: client-service
      stripPrefix: true
    project-service:
      path: /projects/**
      serviceId: project-service
      stripPrefix: true


