server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

zuul:
  ignoredServices: '*'
  routes:
    user-service:
      path: /users/**
      serviceId: user-service
      stripPrefix: true

