server:
  port: 8204

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/condonuitydev
#    username: root
#    password: rootpass
    url: jdbc:mysql://condonuitydev.mysql.database.azure.com:3306/condonuitydev?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: condonuitydbuser@condonuitydev
    password: A#C<)}5gCnP8qQv

spring.jpa:
  hibernate:
    connection:
      charset: utf8
      useUnicode: true
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  show-sql: true

